<section class="help-module f-fix">
    <div class="small-wrapper-m overflow-hidden">
	<div class="text-box col to-load-b">
	    <h3 class="title h1"><?php echo $this->getData('title') ?></h3>
	    <p class="h4 c-dark-gray sub-heading"><?php echo $this->getData('subtitle') ?></p>
	    <p><?php echo $this->getData('paragraph') ?></p>
	    <div class="actions">
		<a href="<?php echo $this->getData('ctalink1') ?>" class="btn gray marR20"><span><?php echo $this->getData('ctatitle1') ?></span></a>
		<a href="<?php echo $this->getData('ctalink2') ?>" class="btn gray"><span><?php echo $this->getData('ctatitle2') ?></span></a>
	    </div>
	</div>
    </div>
</section>